version: '3'
services:
  app:
    build:
      args:
        user: laravel_user
        uid: 1000
      context: .
      dockerfile: dockerfiles/Dockerfile
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - '.:/var/www'
    networks:
      - app_network
    environment:
      APP_ENV: local
      APP_DEBUG: true
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: '${DB_DATABASE}'
      DB_USERNAME: '${DB_USERNAME}'
      DB_PASSWORD: '${DB_PASSWORD}'
    depends_on:
      - mysql

  server:
    image: nginx:alpine
    container_name: server
    restart: unless-stopped
    ports:
      - 6162:80
    depends_on:
      - app
    volumes:
      - ./:/var/www
      - ./dockerfiles/nginx/:/etc/nginx/conf.d
    networks:
      - app_network

  mysql:
    image: 'mysql:8.0'
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
    volumes:
      - 'ercas_mysql_data:/var/lib/mysql'
    networks:
      - app_network

  phpmyadmin:
    image: phpmyadmin:5.2.1-apache
    restart: unless-stopped
    ports:
      - "8383:80"
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: '${DB_USERNAME}'
      PMA_PASSWORD: '${DB_PASSWORD}'
    depends_on:
      - mysql
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
volumes:
  ercas_mysql_data:
    driver: local
