# For more information: https://laravel.com/docs/sail
version: '3'
services:
    app:
        build:
          args:
            user: laravel_user
            uid: 1000
          context: ./dockerfiles
          dockerfile: Dockerfile
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - '.:/var/www'
        networks:
            - ercas_network
        depends_on:
            - mysql


    server:
      image: nginx:alpine
      container_name: server
      restart: unless-stopped
      ports:
        - 6162:80
      depends_on:
        - app
      volumes:
        - ./:/var/www
        - ./dockerfiles/nginx/:/etc/nginx/conf.d
      networks:
        - ercas_network

    mysql:
        image: 'mysql:8.0'
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
        volumes:
            - 'ercas_mysql_data:/var/lib/mysql'
        networks:
            - ercas_network

    phpmyadmin:
      image: phpmyadmin:5.2.1-apache
      restart: unless-stopped
      ports:
        - "8383:80"
      environment:
        PMA_HOST: mysql
        PMA_PORT: 3306
        PMA_USER: '${DB_USERNAME}'
        PMA_PASSWORD: '${DB_PASSWORD}'
      depends_on:
        - mysql
      networks:
        - ercas_network

networks:
    ercas_network:
        driver: bridge
volumes:
    ercas_mysql_data:
        driver: local
